application: strange-team-108212
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.application

libraries:
  - name: jinja2
    version: latest

  - name: PIL
    version: "1.1.7"